Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -18,14 +18,20 @@ steps:
   displayName: 'npm install and build'
  
 - script: |
-    URLS_COMMA_SEPARATED=https://www.uts.edu.au
+    URL=https://www.uts.edu.au
     # Install the Axe CLI accessibility testing tool
-    npm install -g axe-cli
-    axe --help
+    #npm install -g axe-cli
+    #axe --help
+    docker pull gcr.io/check-accessibility/check-accessibility:0.1
 
     # Run the Axe accessibility tests (if there's more pages to test, just give it a comma-separated list of URLs)
     # Appending --exit will cause the tests to exit 1 if problems are found. This could be handy but I'm not using it yet
-    axe $URLS_COMMA_SEPARATED --exit
+    #axe $URLS_COMMA_SEPARATED --exit
+    ACCESSIBILITY_PROBLEMS_JSON=`docker run -e URL=$URL gcr.io/check-accessibility/check-accessibility:0.1`
+    echo $ACCESSIBILITY_PROBLEM_JSON
+    
+    # If test fails, exit 1 to fail this step in the pipeline
+    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi
 
-  displayName: 'Run Axe accessibility tests'
+  displayName: 'Run Docker accessibility tests'
   
